### ISSUE TITLE
Spconv Bug

### ISSUE THREAD

**Issue by Son-Goku-gpu** [mit-han-lab/bevfusion#119] opened 2022-08-31 04:12 UTC
Hi, do you have any suggestion for the bug below? Thanks!

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/59384638/187591178-d5064b58-23ee-48df-b527-c2bfde725402.png">

**Comment by kentang-mit** [comment] 2022-08-31 05:32
This might be an OOM problem. You may check out the [solution](https://github.com/mit-han-lab/bevfusion/issues/26) I posted in this issue related to reversing the order of features.

**Comment by Son-Goku-gpu** [comment] 2022-09-01 04:09
I guess it may be related with the cuda, may I know your cuda version for your development?

**Comment by kentang-mit** [comment] 2022-09-01 05:45
Sure. We use CUDA 11.3. I think CUDA 11.x will be fine as long as it matches the version that PyTorch is compiled with.

**Comment by Son-Goku-gpu** [comment] 2022-09-01 06:47
em...All my softwares are installed with cuda version 11.1:
```
Python 3.7
OpenMPI 4.0.4 and mpi4py 3.1.3
Pillow 8.4.0
PyTorch 1.10.1
tqdm 4.42.1
torchpack 0.3.1
mmcv-full 1.4.0
mmdetection 2.25.1
nuscenes-dev-kit latest
```
and still met the same problem. Any advice?

**Comment by kentang-mit** [comment] 2022-09-01 18:51
For the current codebase it is possible that the required memory is larger than 12G. We will publish a new version of the codebase that consumes less GPU memory during training & testing. The testing memory requirement will be much smaller than 12G after that new release. 

Note: one way to confirm whether it is an OOM problem is that you can try the inference for single-modality models.

**Comment by Son-Goku-gpu** [comment] 2022-09-02 06:27
@kentang-mit Thanks. I guess it should be OOM problem, as I tried to replace ops/spconv with sp2.x and it works.

**Comment by kentang-mit** [comment] 2022-09-04 03:29
Hi @Son-Goku-gpu,

Glad to hear that. I'm closing this issue temporarily because the problem is released. Our new release will actually be based on spconv 2.x.

Best,
Haotian

**Closed by kentang-mit** 2022-09-04 03:29 UTC
