### ISSUE TITLE
OptionalCUDAGuard

### ISSUE THREAD

**Issue by FuzhiYang** [mit-han-lab/bevfusion#105] opened 2022-08-17 08:52 UTC
Hi Haotian,

In the recent commit, "OptionalCUDAGuard" is added in mmdet3d/ops/bev_pool/src/bev_pool.cpp. I just wonder what is the purpose of this module? 
I built the code in the old version (without OptionalCUDAGuard). Will this cause some potential errors? 

Thanks,
Fuzhi

**Comment by kentang-mit** [comment] 2022-08-17 15:21
Hi Fuzhi,

This will not cause potential errors if you are not debugging the single BEV pooling op. `OptionalCUDAGuard` is related to the discussions in [this issue](https://github.com/mit-han-lab/bevfusion/issues/63). 

Best,
Haotian

**Comment by FuzhiYang** [comment] 2022-08-18 09:02
Got it. Thank you very much!

**Comment by kentang-mit** [comment] 2022-08-18 17:21
No problem. I'm closing this issue temporarily because the issue is resolved.

**Closed by kentang-mit** 2022-08-18 17:21 UTC
