### ISSUE TITLE
KeyError: 'sample_idx' when i prepare nuscenes

### ISSUE THREAD

**Issue by hehualin-tut** [mit-han-lab/bevfusion#177] opened 2022-10-10 12:41 UTC
HI,This is the problem I am currently experiencing：
i run the command
python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes
![image](https://user-images.githubusercontent.com/92203298/194867879-2ddce7ca-389a-4f54-a0b2-19b19cd717f8.png)
![image](https://user-images.githubusercontent.com/92203298/194868246-2f943280-d33b-4b01-9273-4e757ac6f295.png)
When i debug to it, there is no key 'sample_idx' in the dist 'example'. I don't know why.

**Comment by kentang-mit** [comment] 2022-10-10 16:12
The problem is fixed after we merged https://github.com/mit-han-lab/bevfusion/pull/156.

**Closed by kentang-mit** 2022-10-10 16:12 UTC
