### ISSUE TITLE
When will the code for training the camera only baseline and lidar only baseline be released?

### ISSUE THREAD

**Issue by Richard-LYF** [mit-han-lab/bevfusion#136] opened 2022-09-15 14:53 UTC
When will the code for training the camera only baseline and lidar only baseline be released?

**Comment by kentang-mit** [comment] 2022-09-17 17:23
Thanks for the interest. We are still cleaning the code. Due to some unexpected incident, the code release is slightly delayed. Please stay tuned, thanks for the patience!

**Comment by IAMShashankk** [comment] 2022-09-19 07:52
@kentang-mit Is it possible for you to give us some timeline on this? Earlier it was expected in september. Is it still possbile?

**Comment by kentang-mit** [comment] 2022-09-19 13:48
We are still working hard on it. If eventually we cannot make it, I will release the hyperparameters of these two models you mentioned.

**Comment by RG2806** [comment] 2022-09-19 14:29
@kentang-mit , if releasing only hyperparameters, please do release for Camera+Lidar model as well

**Comment by kentang-mit** [comment] 2022-09-26 15:49
Training details are currently released in [this branch](https://github.com/mit-han-lab/bevfusion/tree/dev/training) and it is under review for merging into the main branch.

For the camera+LiDAR models, I believe it is relatively easy to reproduce the results with the current information we released. We will do a formal code release in the future, together with some memory-efficient features.

**Closed by kentang-mit** 2022-09-26 15:49 UTC
